Выполнено ДЗ spring boot
NataDon17/HW2_Springboot pull request #1
Opened 2023-05-25 15:50 UTC by NataDon17

Проверьте, пожалуйста, ДЗ

2023-05-25 16:32 UTC, OlgaLugacheva requested changes

2023-05-25 16:32 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/lessons/springboot/weblibraryhw/controller/EmployeeController.java
> +    @GetMapping("salary/sum")
/salary/sum 
и далее также

2023-05-25 16:32 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/lessons/springboot/weblibraryhw/service/EmployeeServiceImpl.java
> +                .get();
ну лучше что-то другое использовать, например, исключение бросать

2023-06-05 07:09 UTC, isavinov approved these changes

2023-06-05 08:10 UTC, merged